/*
 * ORION Optimized Rule Integration & Operations Native
 * SPDX-License-Identifier: Apache-2.0
 * SPDX-FileCopyrightText: 2025 ORION contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy at https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Modifications: This file has been modified by ORION contributors. See VCS history.
 */
#pragma once
#include <string>
#include <variant>
#include <optional>

namespace orion::bre::feel {
    using number = double;

    struct Date
    {
        int y{}, m{}, d{};
        auto operator<=>(const Date&) const = default;
    };

    struct Time
    {
        int h{}, m{}, s{};
        auto operator<=>(const Time&) const = default;
    };

    struct DateTime
    {
        Date date;
        Time time;
        auto operator<=>(const DateTime&) const = default;
    };

    struct Duration
    {
        int total_months = 0; // years*12 + months
        long long total_seconds = 0; // days/hours/minutes/seconds in seconds

        // C++20/23: generate all comparisons
        auto operator<=>(const Duration&) const = default;
        // (operator== is implicitly generated by the defaulted <=>)
    };

    // Declared here; implemented in feel_types.cpp
    [[nodiscard]] std::optional<Duration> parse_duration(std::string_view str);

    using Value = std::variant<std::monostate, bool, number, std::string, Date, Time, DateTime, Duration>;

    [[nodiscard]] std::optional<Date> parse_date(std::string_view str);
    [[nodiscard]] std::optional<Time> parse_time(std::string_view str);
    [[nodiscard]] std::optional<DateTime> parse_datetime(std::string_view str);
}
